# Generated by Django 4.2.4 on 2023-12-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider_image',
            old_name='silder_image',
            new_name='slider_image',
        ),
        migrations.RenameField(
            model_name='slider_image',
            old_name='silder_title',
            new_name='slider_title',
        ),
    ]
