# Generated by Django 4.2.4 on 2023-12-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_silder_image_slider_image_slider_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecaher_name', models.CharField(max_length=300)),
                ('tecaher_rank', models.CharField(max_length=300)),
                ('studied_subject', models.CharField(max_length=300)),
                ('institute', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('teacher_image', models.ImageField(upload_to='static/teacher_images/')),
            ],
        ),
    ]
