# Generated by Django 4.2.4 on 2023-12-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_faculty_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_member',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
