# Generated by Django 4.2.4 on 2023-12-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_floating_image_1_floating_image_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testomonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('identity', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
    ]
