# Generated by Django 4.2.4 on 2023-12-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_testomonial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testomonial',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
