# Generated by Django 4.2.4 on 2023-12-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_testomonial_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_name', models.CharField(max_length=300)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='static/notice_pdf/')),
            ],
        ),
    ]
